<?php
// created: 2011-01-10 14:55:20
$sugar_config = array (
  'admin_export_only' => false,
  'authenticationClass' => 'PortalAuthenticate',
  'cache_dir' => 'cache/',
  'calculate_response_time' => true,
  'create_default_user' => false,
  'date_formats' => 
  array (
    'Y-m-d' => '2006-12-23',
    'm-d-Y' => '12-23-2006',
    'd-m-Y' => '23-12-2006',
    'Y/m/d' => '2006/12/23',
    'm/d/Y' => '12/23/2006',
    'd/m/Y' => '23/12/2006',
    'Y.m.d' => '2006.12.23',
    'd.m.Y' => '23.12.2006',
    'm.d.Y' => '12.23.2006',
  ),
  'dbconfigoption' => 
  array (
    'persistent' => true,
    'autofree' => false,
    'debug' => 0,
    'seqname_format' => '%s_seq',
    'portability' => 0,
    'ssl' => false,
  ),
  'default_action' => 'index',
  'default_charset' => 'UTF-8',
  'default_currency_iso4217' => 'USD',
  'default_currency_name' => 'US Dollar',
  'default_currency_symbol' => '$',
  'default_date_format' => 'Y-m-d',
  'default_decimal_seperator' => '.',
  'default_email_client' => 'sugar',
  'default_email_editor' => 'html',
  'default_language' => 'en_us',
  'default_module' => 'Home',
  'default_number_grouping_seperator' => ',',
  'default_password' => '',
  'default_theme' => 'Sugar',
  'default_time_format' => 'H:i',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'disable_export' => false,
  'disable_persistent_connections' => 'false',
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => false,
  'export_delimiter' => ',',
  'faq_cache_time' => '86400000',
  'history_max_viewed' => 10,
  'host_name' => 'html2.com',
  'i18n_test' => false,
  'import_dir' => 'cache/import/',
  'installer_locked' => true,
  'js_custom_version' => '',
  'languages' => 
  array (
    'en_us' => 'US English',
  ),
  'large_scale_test' => false,
  'list_max_entries_per_page' => 20,
  'list_max_entries_per_subpanel' => 10,
  'lock_default_user_name' => false,
  'lock_homepage' => false,
  'lock_subpanels' => false,
  'log_dir' => '.',
  'log_file' => 'sugarcrm.log',
  'log_memory_usage' => false,
  'login_nav' => false,
  'max_dashlets_homepage' => '10',
  'parent_site_url' => 'http://html2.com/rlsugarEnt',
  'portal_password' => '3Fbc/ifn',
  'portal_username' => 'spadmin',
  'require_accounts' => true,
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'session_dir' => '',
  'site_url' => 'http://html2.com/sugarcsp',
  'slow_query_time_msec' => '100',
  'sugar_version' => '6.1.0',
  'sugarbeet' => true,
  'time_formats' => 
  array (
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
  ),
  'tmp_dir' => 'cache/xml/',
  'translation_string_prefix' => false,
  'unique_key' => '',
  'upload_badext' => 
  array (
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'pl',
    5 => 'cgi',
    6 => 'py',
    7 => 'asp',
    8 => 'cfm',
    9 => 'js',
    10 => 'vbs',
    11 => 'html',
    12 => 'htm',
  ),
  'upload_dir' => 'cache/upload/',
  'upload_maxsize' => 3000000,
  'use_php_code_json' => true,
  'verify_client_ip' => true,
);
?>
